import json


# Function to distribute rules to CAs (prints the output for now)
def distribute_rule(rule_data):
    """
    Distribute the rule to the appropriate CAs.

    Args:
        rule_data (dict): The rule data generated by RuleAgent.
    """
    print("\n--- Rule Distributor Output ---")
    print(json.dumps(rule_data, indent=4))
    print("Rule distribution simulated (waiting for CAs).")


# Example usage of RuleDistributorAgent
if __name__ == "__main__":
    # Simulate receiving the rule from RuleAgent
    example_rule_data = {
        "rule": "If demand is high, allocate additional onboarding resources and notify stakeholders.",
        "class": "high",
        "context": "onboarding process",
    }

    distribute_rule(example_rule_data)
